#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
library(shiny)
library(RefManageR)
library(revtools)
library(stringr)

bibliography <- revtools::read_bibliography("../LiteratureReview.bib")

fields <- c("simplificationtype" = "",
            "simsoftware" = "",
            "studytype" = "",
            "systemtype" = "",
            "apparea" = "",
            "complexity" = "",
            "motivation" = "",
            "complexitymeasure" = "",
            "validationmeasure" = "",
            "efficacymeasure" = "",
            "additional_notes" = "")

create_empty_frame <- function() {
    data_form <- data.frame("label" = bibliography$label, as.list(fields))
}

if (file.exists("saved_progress.RData")) {
    data_form <- readRDS("saved_progress.RData")
    if (nrow(data_form) != nrow(bibliography)) {
        data_form <- create_empty_frame()
    }
} else {
    data_form <- create_empty_frame()
}

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Data extraction form"),

    sidebarLayout(
        sidebarPanel(
            h2("Meta-data"),
            verbatimTextOutput("meta"),
            fluidRow(column(6, div(style = "text-align:center", actionButton("reset_btn", "Reset", class="btn-warning"))),
                     column(6, div(style = "text-align:center",downloadButton("download_btn"))))
        ),
        mainPanel(
            # ID, autogenerated (label)
            fluidRow(
                div(style = "display:inline-block", actionButton("back_btn", "Back", icon = shiny::icon("angle-left"))),
                div(style = "display:inline-block", uiOutput("status")),
                div(style = "display:inline-block", actionButton("next_btn", "Next", icon = shiny::icon("angle-right")))
            ),
            br(),
            fluidRow(
            # Simplification Type
            column(6,
                textAreaInput("simplificationtype", "Simplification Type"),
                # Simulation software
                textAreaInput("simsoftware", "Simulation Software"),
                # Study type
                textAreaInput("studytype", "Study Type"),
                # System type
                textAreaInput("systemtype", "System Type"),
                # Application area
                textAreaInput("apparea", "Application Area"),
                # Size and complexity
                textAreaInput("complexity", "Size and complexity"),
                # Motivation
                textAreaInput("motivation", "Motivation")),
            column(6,
                # Complexity measure
                textAreaInput("complexitymeasure", "Complexity Measure"),
                # Validation measure
                textAreaInput("validationmeasure", "Validation Measure"),
                # Efficacy measure
                textAreaInput("efficacymeasure", "Efficacy Measure"),
                hr(),
                textAreaInput("additional_notes", "Additional Notes"),
                actionButton("save_btn", "Save", class = "btn-primary")
            ))
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {
    extraction_data <- reactiveValues("data" = data_form, current_text = 1)

    title_change <- reactive({
        paste("Status", extraction_data$current_text, "of", nrow(bibliography))

    })

    observeEvent(extraction_data$current_text,  {
        for (type in names(fields)) {
            updateTextAreaInput(session, type, value = extraction_data$data[extraction_data$current_text,type])
        }
        output$status <- renderText({title_change()})
    })

    observeEvent(input$back_btn, {
        if (extraction_data$current_text > 1) {
            extraction_data$current_text <- extraction_data$current_text - 1
        }
    })

    observeEvent(input$next_btn, {
        if (extraction_data$current_text < nrow(extraction_data$data)) {
            extraction_data$current_text <- extraction_data$current_text + 1
        }
    })

    observeEvent(input$save_btn, {
        # Save values to the data frame
        for (type in names(fields)) {
            extraction_data$data[extraction_data$current_text,type] <- input[[type]]
        }
        saveRDS(extraction_data$data, file = "saved_progress.RData", compress = "xz")
    })

    observeEvent(input$reset_btn, {
        # Reset
        showModal(modalDialog(
            title = "Somewhat important message",
            textInput("validation", "Reset validation",
                      placeholder = 'Input reset here to reset the database'),
            easyClose = FALSE,
            footer = tagList(
                modalButton("Cancel"),
                actionButton("ok", "OK")
            )
        ))
    })

    observeEvent(input$ok, {
        # Check that data object exists and is data frame.
        if (!is.null(input$validation) && nzchar(input$validation) && input$validation =="reset") {
            extraction_data$data <- create_empty_frame()
        }
        removeModal()
    })

    output$download_btn <- downloadHandler(
        filename = function() {
            paste("data-", Sys.Date(), ".csv", sep="")
        },
        content = function(file) {
            write.csv(extraction_data$data, file, row.names = FALSE)
        }
    )

    output$meta <-  renderText({paste(str_to_title(bibliography$title[extraction_data$current_text]),
                                        bibliography$author[extraction_data$current_text],
                                        bibliography$year[extraction_data$current_text],
                                        bibliography$journal[extraction_data$current_text], sep = "\n")})
}

# Run the application
shinyApp(ui = ui, server = server)
